server:
    port: 8090

spring:
    servlet:
      multipart:
        max-file-size: 4MB
        max-request-size: 4MB
    mvc:
      pathmatch:
        matching:
          strategy: ANT_PATH_MATCHER
    datasource:
       url: jdbc:postgresql://localhost:5432/rentals
       username: postgres
       password: 1234
       hikari:
        auto-commit: false
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
       ddl-auto: update
